name: Deploy File to Local System
on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
jobs:
  deploy_to_local:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Deploy file to local system
        uses: appleboy/ssh-action@master
        with:
          host: localhost
          username: opraveen
          key: ${{ secrets.SSH_SECURE_SECRET }}
          port: 22
          script: |
            scp $GITHUB_WORKSPACE/output.csv opraveen@localhost:/home/opraveen/airflow_workspace
