name: Removing Duplicates

on:
  push:
    branches:
      - main  # Or the branch you want to trigger the workflow on
      - Testing-branch

jobs:
  remove_duplicates:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Choose the Python version you need

    - name: Install Dependencies
      run: |
        pip install pyspark

    - name: Remove Duplicates and Save to CSV
      run: python spark_non_duplicate.py

    - name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Remove duplicates from CSV file"
        commit_user_name: "GitHub Actions"
        commit_user_email: "actions@github.com"
        commit_author: "GitHub Actions <actions@github.com>"
        branch: ${{ github.ref }}

    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
