name: PySpark Job

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  run_pyspark_job:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    env:
      INPUT_CSV_PATH: "netflix_titles.csv"
      OUTPUT_CSV_PATH: "op_output.csv"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python environment
        with:
          python-version: '3.x'  # Use Python 3.x

      - name: Install dependencies
        run: |
          pip install pyspark

      - name: Run PySpark script
        run: python test_trans.py
        
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated commit: Update output CSV file"
          branch: main
